### ISSUE TITLE
"sudo infrasim init -f" reports error on a clean system

### ISSUE THREAD

**Issue by fub2** [InfraSIM/infrasim-compute#243]
Traceback (most recent call last):
  File "/usr/local/bin/infrasim", line 6, in <module>
    cli.command_handler()
  File "/usr/local/lib/python2.7/dist-packages/infrasim/cli.py", line 344, in command_handler
    infrasim_init(args.type, args.skip_installation, args.force, args.infrasim_home, args.config_file)
  File "/usr/local/lib/python2.7/dist-packages/infrasim/init.py", line 105, in infrasim_init
    destroy_existing_nodes()
  File "/usr/local/lib/python2.7/dist-packages/infrasim/init.py", line 87, in destroy_existing_nodes
    nodes = os.listdir(config.infrasim_home)
OSError: [Errno 2] No such file or directory: '/home/vxrail/.infrasim'

**Comment by turtle-fly** [comment]
@chenge3

**Comment by chenge3** [comment]
@turtle-fly this bug can be fixed with PR#241:
https://github.com/InfraSIM/infrasim-compute/pull/241
