### ISSUE TITLE
how to run unit tests for development?

### ISSUE THREAD

**Issue by heckj** [InfraSIM/infrasim-compute#52]
Hey @fub2 

Enjoyed the demo and walk through, so I tried to spin up a local environment to poke at things from a unit/functional test level. I'm not entirely clear on how to run the unit tests - was hoping you could point me in the right direction.

Here's what I did:

* create a Vagrant Ubuntu 16.04 instance to work within
`vagrant init ubuntu/wily64 && vagrant up && vagrant ssh`

Within that setup:
```
sudo apt-get install git
# dependencies per README
sudo apt-get install socat ipmitool qemu openipmi python-pip libssl-dev libssh-dev libpython-dev libffi-dev sgabios
# try starting with virtualenv
sudo apt-get install python-virtualenv

git clone https://github.com/infrasim/infrasim-compute
cd infrasim-compute
virtualenv .venv
source .venv/bin/activate
pip install -r requirements.txt
```

And from here I wasn't sure - when I tried `nosetests test/unit` I had some passes, and some failures. Does the development/test setup expect code to be in slightly different positions, or something additionally installed or running?

Would you recommend a different path to set up for basic development?

**Comment by sharkconi** [comment]
@heckj  
to run the unittest, cd infrasim-compute && ./.unittests 
to run the function test,  cd infrasim-compute  && ./.functiontests

You can find these two hidden scripts for unittest and functiontest

Thanks

**Comment by heckj** [comment]
Thanks @sharkconi  - do they need to be run as root by chance? 

With this described setup, I'm getting a few unit test errors that seem to be very specific to the setup/construction of the local system:

`cd ~/infrasim-compute && ./.unittests`:

```
======================================================================
FAIL: test_core_process.test_qemu_exist
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/vagrant/infrasim-compute/.venv/local/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/vagrant/infrasim-compute/test/unit/test_core_process.py", line 27, in test_qemu_exist
    assert False
AssertionError:
-------------------- >> begin captured logging << --------------------
nose_cov: DEBUG: nose-cov begin
root: ERROR: which /usr/local/bin/qemu-system-x86_64:
--------------------- >> end captured logging << ---------------------

======================================================================
FAIL: test_core_process.test_ipmi_exist
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/vagrant/infrasim-compute/.venv/local/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/vagrant/infrasim-compute/test/unit/test_core_process.py", line 34, in test_ipmi_exist
    assert False
AssertionError:
-------------------- >> begin captured logging << --------------------
root: ERROR: which /usr/local/bin/ipmi_sim:
--------------------- >> end captured logging << ---------------------

======================================================================
FAIL: test_core_process.test_socat_process_start
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/vagrant/infrasim-compute/.venv/local/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/vagrant/infrasim-compute/test/unit/test_core_process.py", line 52, in test_socat_process_start
    assert False
AssertionError:
-------------------- >> begin captured logging << --------------------
root: INFO: socat start
root: ERROR: which /usr/local/bin/ipmi_sim:
--------------------- >> end captured logging << ---------------------

======================================================================
FAIL: test_create_delete_macvtap (test_qemu.qemu_functions)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/vagrant/infrasim-compute/test/unit/test_qemu.py", line 162, in test_create_delete_macvtap
    assert False
AssertionError:
-------------------- >> begin captured logging << --------------------
root: ERROR: ip link add link eth0 name macvtap0 type macvtap mode bridge:RTNETLINK answers: Operation not permitted

--------------------- >> end captured logging << ---------------------

======================================================================
FAIL: test_set_disks_disk_size_8G (test_qemu.qemu_functions)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/vagrant/infrasim-compute/test/unit/test_qemu.py", line 125, in test_set_disks_disk_size_8G
    assert False
AssertionError:
-------------------- >> begin captured logging << --------------------
root: ERROR: qemu-img create -f qcow2 /home/vagrant/.infrasim/sda.img 8G:qemu-img: /home/vagrant/.infrasim/sda.img: Could not create file: No such file or directory

--------------------- >> end captured logging << ---------------------
```


The code in ./functiontests looks like there's a slight error in it - as written, it doesn't find the "infrasim" module to import:

```
ERROR: Failure: ImportError (No module named infrasim)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/vagrant/infrasim-compute/.venv/local/lib/python2.7/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/home/vagrant/infrasim-compute/.venv/local/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/home/vagrant/infrasim-compute/.venv/local/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/vagrant/infrasim-compute/test/functional/test_ipmi_command_response.py", line 20, in <module>
    from infrasim import qemu
ImportError: No module named infrasim
```

I stuck up a PR to make these two consistent (https://github.com/InfraSIM/infrasim-compute/pull/53), which gets things closer - it at least finds the module with the scripts now, but still a number of errors. Wasn't sure if it was meant/allowed to run as a normal user or if some of what it was doing required `root` access to the local OS:

```
test_set_bmc_vendor (test_configuration_change.test_configuration_change) ... FAIL
test_set_cpu_family (test_configuration_change.test_configuration_change) ... FAIL
test_set_disk_drive (test_configuration_change.test_configuration_change) ... ERROR
test_set_memory_capacity (test_configuration_change.test_configuration_change) ... FAIL
test_set_vcpu (test_configuration_change.test_configuration_change) ... FAIL
2016/08/10 19:04:19 socat[18049] E symlink("/dev/pts/1", "/etc/infrasim/pty0"): No such file or directory
ERROR
2016/08/10 19:04:22 socat[18055] E symlink("/dev/pts/1", "/etc/infrasim/pty0"): No such file or directory
ERROR

======================================================================
ERROR: test_set_disk_drive (test_configuration_change.test_configuration_change)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/vagrant/infrasim-compute/test/functional/test_configuration_change.py", line 88, in test_set_disk_drive
    vm.set_disks('test.config')
  File "/home/vagrant/infrasim-compute/infrasim/qemu.py", line 173, in set_disks
    raise e
CommandRunFailed: 'qemu-img create -f qcow2 /home/vagrant/.infrasim/sda.img 32G:qemu-img: /home/vagrant/.infrasim/sda.img: Could not create file: No such file or directory\n'
-------------------- >> begin captured logging << --------------------
root: ERROR: qemu-img create -f qcow2 /home/vagrant/.infrasim/sda.img 32G:qemu-img: /home/vagrant/.infrasim/sda.img: Could not create file: No such file or directory

--------------------- >> end captured logging << ---------------------

======================================================================
ERROR: test suite for <class 'test_ipmi_command_response.test_ipmicommand_response'>
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/vagrant/infrasim-compute/.venv/local/lib/python2.7/site-packages/nose/suite.py", line 209, in run
    self.setUp()
  File "/home/vagrant/infrasim-compute/.venv/local/lib/python2.7/site-packages/nose/suite.py", line 292, in setUp
    self.setupContext(ancestor)
  File "/home/vagrant/infrasim-compute/.venv/local/lib/python2.7/site-packages/nose/suite.py", line 315, in setupContext
    try_run(context, names)
  File "/home/vagrant/infrasim-compute/.venv/local/lib/python2.7/site-packages/nose/util.py", line 471, in try_run
    return func()
  File "/home/vagrant/infrasim-compute/test/functional/test_ipmi_command_response.py", line 54, in setUpClass
    ipmi.start_ipmi("quanta_d51")
  File "/home/vagrant/infrasim-compute/infrasim/ipmi.py", line 22, in start_ipmi
    ipmi_cmd = get_ipmi()
  File "/home/vagrant/infrasim-compute/infrasim/ipmi.py", line 12, in get_ipmi
    raise CommandNotFound("/usr/local/bin/ipmi_sim")
CommandNotFound: '/usr/local/bin/ipmi_sim'
-------------------- >> begin captured logging << --------------------
root: INFO: socat start
root: ERROR: which /usr/local/bin/ipmi_sim:
--------------------- >> end captured logging << ---------------------

======================================================================
ERROR: test suite for <class 'test_ipmi_console.test_ipmi_console'>
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/vagrant/infrasim-compute/.venv/local/lib/python2.7/site-packages/nose/suite.py", line 209, in run
    self.setUp()
  File "/home/vagrant/infrasim-compute/.venv/local/lib/python2.7/site-packages/nose/suite.py", line 292, in setUp
    self.setupContext(ancestor)
  File "/home/vagrant/infrasim-compute/.venv/local/lib/python2.7/site-packages/nose/suite.py", line 315, in setupContext
    try_run(context, names)
  File "/home/vagrant/infrasim-compute/.venv/local/lib/python2.7/site-packages/nose/util.py", line 471, in try_run
    return func()
  File "/home/vagrant/infrasim-compute/test/functional/test_ipmi_console.py", line 72, in setUpClass
    ipmi.start_ipmi('quanta_d51')
  File "/home/vagrant/infrasim-compute/infrasim/ipmi.py", line 22, in start_ipmi
    ipmi_cmd = get_ipmi()
  File "/home/vagrant/infrasim-compute/infrasim/ipmi.py", line 12, in get_ipmi
    raise CommandNotFound("/usr/local/bin/ipmi_sim")
CommandNotFound: '/usr/local/bin/ipmi_sim'
-------------------- >> begin captured logging << --------------------
root: INFO: socat start
root: ERROR: which /usr/local/bin/ipmi_sim:
root: INFO: socat start
root: ERROR: which /usr/local/bin/ipmi_sim:
--------------------- >> end captured logging << ---------------------

======================================================================
FAIL: test_set_bmc_vendor (test_configuration_change.test_configuration_change)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/vagrant/infrasim-compute/test/functional/test_configuration_change.py", line 68, in test_set_bmc_vendor
    assert '-name dell_c6320' in str_result
AssertionError

======================================================================
FAIL: test_set_cpu_family (test_configuration_change.test_configuration_change)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/vagrant/infrasim-compute/test/functional/test_configuration_change.py", line 55, in test_set_cpu_family
    assert 'qemu-system-x86_64' in str_result
AssertionError

======================================================================
FAIL: test_set_memory_capacity (test_configuration_change.test_configuration_change)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/vagrant/infrasim-compute/test/functional/test_configuration_change.py", line 81, in test_set_memory_capacity
    assert 'qemu-system-x86_64' in str_result
AssertionError

======================================================================
FAIL: test_set_vcpu (test_configuration_change.test_configuration_change)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/vagrant/infrasim-compute/test/functional/test_configuration_change.py", line 42, in test_set_vcpu
    assert 'qemu-system-x86_64' in str_result
AssertionError

----------------------------------------------------------------------
Ran 5 tests in 6.163s

FAILED (errors=3, failures=4)
```

**Comment by sharkconi** [comment]
@heckj  You have to "sudo python setup.py install && sudo infrasim-init" first.

Thanks
